const state={layout:{lists:[]},quotes:{},config:{},drag:null};const $=s=>document.querySelector(s);const listTpl=$('#listTemplate'),rowTpl=$('#rowTemplate');
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok)throw new Error((await r.text()).trim()||r.statusText);if(r.status===204)return;return r.json()}
function fmtPrice(v){return v>0?v.toFixed(v<1?4:2):'—'}function compact(v){if(!v)return'—';return Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:2}).format(v)}
function allSymbols(){return state.layout.lists.flatMap(l=>l.Items.map(i=>i.Symbol))}function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function render(){const board=$('#board');board.replaceChildren();const sel=$('#listSelect');sel.replaceChildren();state.layout.lists.forEach((list,li)=>{const opt=new Option(list.Name,list.ID);sel.add(opt);const section=listTpl.content.firstElementChild.cloneNode(true);section.dataset.id=list.ID;section.querySelector('.color').style.background=list.Color||'#4cc9f0';const name=section.querySelector('.list-name');name.value=list.Name;name.onchange=()=>{list.Name=name.value.trim()||'UNTITLED';saveLayout()};section.querySelector('.count').textContent=`${list.Items.length} TICKERS`;section.querySelector('.remove-list').onclick=()=>{if(list.Items.length)return toast('Move or delete tickers first');state.layout.lists.splice(li,1);saveLayout()};const rows=section.querySelector('.rows');if(!list.Items.length){rows.innerHTML='<div class="empty">DROP TICKERS HERE OR ADD ONE ABOVE</div>'}list.Items.forEach((item,ii)=>rows.appendChild(row(item,list,li,ii)));rows.ondragover=e=>e.preventDefault();rows.ondrop=e=>drop(e,list,list.Items.length);board.appendChild(section)});paintAll()}
function row(item,list,li,ii){const el=rowTpl.content.firstElementChild.cloneNode(true);el.dataset.id=item.ID;el.querySelector('.symbol').textContent=item.Symbol;el.querySelector('.note').textContent=item.Note||'CLICK → CHART + TAPE';el.querySelectorAll('.select').forEach(b=>b.onclick=()=>select(item.Symbol));el.querySelector('.delete').onclick=async()=>{await api('/api/tickers/'+encodeURIComponent(item.ID),{method:'DELETE'});list.Items.splice(ii,1);render()};el.querySelector('.up').onclick=()=>move(list,ii,-1);el.querySelector('.down').onclick=()=>move(list,ii,1);el.ondragstart=()=>{state.drag={item,from:list};el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging');el.ondragover=e=>{e.preventDefault();el.classList.add('drop-target')};el.ondragleave=()=>el.classList.remove('drop-target');el.ondrop=e=>{e.preventDefault();e.stopPropagation();drop(e,list,ii)};return el}
function move(list,i,d){const j=i+d;if(j<0||j>=list.Items.length)return;[list.Items[i],list.Items[j]]=[list.Items[j],list.Items[i]];saveLayout()}
function drop(e,list,index){if(!state.drag)return;const {item,from}=state.drag;from.Items=from.Items.filter(x=>x.ID!==item.ID);if(from===list&&from.Items.length<index)index--;list.Items.splice(Math.max(0,index),0,item);state.drag=null;saveLayout()}
async function saveLayout(){try{state.layout=await api('/api/layout',{method:'PUT',body:JSON.stringify(state.layout)});render()}catch(e){toast(e.message)}}
async function select(symbol){const tab=window.open('about:blank','_blank');try{const out=await api('/api/select',{method:'POST',body:JSON.stringify({symbol})});if(tab)tab.location=out.chart_url;if(!out.tape_ok)toast('Chart opened · tape tool unavailable')}catch(e){if(tab)tab.close();toast(e.message)}}
function paintAll(){document.querySelectorAll('.ticker').forEach(el=>{const item=state.layout.lists.flatMap(x=>x.Items).find(x=>x.ID===el.dataset.id);const q=state.quotes[item?.Symbol];if(!q)return;el.querySelector('.price').textContent=fmtPrice(q.last);const ch=el.querySelector('.change');ch.textContent=(q.change_pct>=0?'+':'')+q.change_pct.toFixed(2)+'%';ch.className='change '+(q.change_pct>=0?'positive':'negative');el.querySelector('.volume').textContent=compact(q.volume);draw(el.querySelector('.map'),q.history||[])})}
function draw(c,pts){const d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d}const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);x.fillStyle='#0a0d11';x.fillRect(0,0,w,h);x.fillStyle='#17212a';x.fillRect(w*.18,0,w*.64,h);x.strokeStyle='#27313b';x.setLineDash([2,3]);[.18,.82].forEach(v=>{x.beginPath();x.moveTo(w*v,0);x.lineTo(w*v,h);x.stroke()});x.setLineDash([]);if(pts.length<2)return;let lo=Math.min(...pts.map(p=>p.p)),hi=Math.max(...pts.map(p=>p.p));if(hi===lo){hi+=.01;lo-=.01}x.strokeStyle=pts.at(-1).p>=pts[0].p?'#35e68a':'#ff5263';x.lineWidth=2;x.beginPath();pts.forEach((p,i)=>{const px=i/(pts.length-1)*w,py=h-4-(p.p-lo)/(hi-lo)*(h-8);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
$('#addForm').onsubmit=async e=>{e.preventDefault();const input=$('#symbolInput'),symbol=input.value.trim().toUpperCase();if(!symbol)return;try{await api('/api/tickers',{method:'POST',body:JSON.stringify({symbol,listID:$('#listSelect').value})});input.value='';await load();input.focus()}catch(e){toast(e.message)}};
$('#newList').onclick=()=>{const name=prompt('Watchlist name');if(!name)return;state.layout.lists.push({ID:'list-'+Date.now(),Name:name.trim().toUpperCase(),Color:['#4cc9f0','#f72585','#9bdb4d','#ff9f1c'][state.layout.lists.length%4],Items:[]});saveLayout()};
document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName)){e.preventDefault();$('#symbolInput').focus()}});
async function load(){const s=await api('/api/state');Object.assign(state,s);render();status(s.status)}function status(s){const e=$('#status');e.className='status '+s.state;e.querySelector('span').textContent=(s.state||'offline').toUpperCase()+(s.message?' · '+s.message:'')}
const events=new EventSource('/api/events');events.onmessage=e=>{const m=JSON.parse(e.data);state.quotes=m.quotes||{};if(m.layout){state.layout=m.layout;render()}status(m.status);paintAll()};events.onerror=()=>status({state:'offline',message:'reconnecting'});load().catch(e=>toast(e.message));
